MouseMove 40, 670
Click left
MouseMove 300, 670
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
MouseMove 200, 1000
Sleep 100
Click down
MouseMove 950, 770
Click up
Sleep 100
MouseMove 200, 1000
Click, left
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
Click, WheelUp
